#!/usr/bin/env bash
# Generate Docker build files that trust the Claude Code cloud egress proxy CA.
#
# Usage: docker-proxy-ca.sh <repo-dir> <out-dir> <ca-bundle>
#
# In Claude Code cloud sessions, HTTPS traffic from containers goes through an
# egress proxy that re-terminates TLS, so every HTTPS client inside a build
# (pip/uv, npm, bower, git, wget) must trust the session CA bundle. This copies
# the dev Dockerfiles and, after each FROM line, installs the bundle into the
# system trust store and points the usual CA env vars at it. The repo's own
# Dockerfiles are untouched; use the generated compose override alongside
# docker-compose.yml.
set -euo pipefail

REPO="$1"
OUT="$2"
CA_BUNDLE="$3"

rm -rf "$OUT/proxy-ca"
mkdir -p "$OUT/proxy-ca/system-certs"
cp "$CA_BUNDLE" "$OUT/proxy-ca/ca-bundle.crt"
# One cert per file, as update-ca-certificates expects. Containers are served
# certs from more than one proxy CA, so trust the whole session bundle rather
# than picking CAs by name.
awk -v dir="$OUT/proxy-ca/system-certs" '
  /BEGIN CERTIFICATE/ { n++; f = sprintf("%s/proxy-ca-%03d.crt", dir, n) }
  n { print > f }
  /END CERTIFICATE/ { close(f) }
' "$CA_BUNDLE"

python3 - "$REPO" "$OUT" <<'PY'
import re
import sys

repo, out = sys.argv[1], sys.argv[2]
bundle = "/etc/ssl/proxy-ca-bundle.crt"
inject = "\n".join([
    "# --- generated: trust the Claude Code cloud egress proxy CA ---",
    # update-ca-certificates also runs whenever the ca-certificates package is
    # installed later, which covers tools that only read the system store
    # (e.g. GnuTLS wget).
    "COPY --from=proxy-ca system-certs/ /usr/local/share/ca-certificates/proxy-ca/",
    f"COPY --from=proxy-ca ca-bundle.crt {bundle}",
    "RUN if command -v update-ca-certificates >/dev/null 2>&1; then update-ca-certificates >/dev/null 2>&1; fi",
    f"ENV SSL_CERT_FILE={bundle} \\",
    f"    REQUESTS_CA_BUNDLE={bundle} \\",
    f"    PIP_CERT={bundle} \\",
    f"    NODE_EXTRA_CA_CERTS={bundle} \\",
    f"    GIT_SSL_CAINFO={bundle} \\",
    f"    CURL_CA_BUNDLE={bundle}",
    "# --- end generated ---",
])

for service in ("django", "nodejs"):
    src = open(f"{repo}/docker/dev/{service}/Dockerfile").read().splitlines()
    lines = []
    for line in src:
        lines.append(line)
        if re.match(r"^FROM\s", line):
            lines.append(inject)
    with open(f"{out}/{service}.Dockerfile", "w") as f:
        f.write("\n".join(lines) + "\n")
PY

cat > "$OUT/docker-compose.proxy-ca.yml" <<EOF
# Generated by .claude/hooks/docker-proxy-ca.sh; do not edit.
services:
  django:
    build:
      dockerfile: $OUT/django.Dockerfile
      additional_contexts:
        proxy-ca: $OUT/proxy-ca
  nodejs:
    build:
      dockerfile: $OUT/nodejs.Dockerfile
      additional_contexts:
        proxy-ca: $OUT/proxy-ca
EOF
