# Number of days of inactivity a Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity a Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - priority-high
  - critical

# Label to use when marking as stale
staleLabel: inactivity

pulls:
  # Comment to post on pull requests when marking as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.

  # Comment to post when closing a stale Pull Request.
  closeComment: >
    This pull request has been automatically closed as there is no further activity. Thank you
    for your contributions.
