# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'remove_affiliation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_avatar/'),
        ),
    ]
