# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-21 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_profile")]

    operations = [
        migrations.RemoveField(
            model_name="useraffliation", name="affiliation"
        ),
        migrations.RemoveField(model_name="useraffliation", name="user"),
        migrations.DeleteModel(name="Affiliation"),
        migrations.DeleteModel(name="UserAffliation"),
    ]
