# Generated by Django 2.2.20 on 2022-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_jwt_access_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='expires_at',
            field=models.PositiveIntegerField(default=86400),
        ),
    ]
