# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200304_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='./frontend/src/images/pro-pic.png', upload_to='./media'),
        ),
    ]
