# Generated by Django 2.2.20 on 2026-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_profile_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_bounced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_bounced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
