# Generated by Django 2.2.20 on 2026-02-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_profile_address_fields"),
    ]

    operations = []
