# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-20 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avatarimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvatarImage',
        ),
    ]
