# Generated by Django 2.2.20 on 2026-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_email_bounced_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique "
                "UNIQUE (email);"
            ),
            reverse_sql=(
                "ALTER TABLE auth_user DROP CONSTRAINT auth_user_email_unique;"
            ),
        ),
    ]
