# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-20 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200220_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(default='/home/bruh/Pictures/HRL.png', upload_to='test_folder'),
        ),
    ]
