# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200220_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(default='/frontend/src/images/pro-pic.png', upload_to='test_folder'),
        ),
    ]
