doc-warnings: true
test-warnings: false
strictness: high
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements/dev.txt
  - requirements/prod.txt
ignore-paths:
  - docs
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 2
