version: 2

sphinx:
  configuration: docs/source/conf.py
  builder: html

formats:
  - epub
  - pdf

python:
   version: 3.6
   install:
   - requirements: requirements/readthedocs.txt
   system_packages: true