version: 2

build:
  os: ubuntu-22.04 # required since Oct 2023
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements/readthedocs.txt

sphinx:
  configuration: docs/source/conf.py
  builder: html
  formats:
    - epub
    - pdf
