version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements/readthedocs.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf
