version: "3"
services:

  django:
    image: 937891341272.dkr.ecr.us-east-1.amazonaws.com/evalai-backend:latest
    container_name: django
    env_file:
      - docker/prod/docker.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - "8000:8000"

  worker:
    image: 937891341272.dkr.ecr.us-east-1.amazonaws.com/evalai-worker:latest
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    depends_on:
      - django
    env_file:
      - docker/prod/docker.env

  nodejs:
    image: 937891341272.dkr.ecr.us-east-1.amazonaws.com/evalai-nodejs:latest
    container_name: nodejs
    build:
      context: ./
      dockerfile: docker/prod/nodejs/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8888:8888"
      - "80:80"
    volumes:
      - /code/node_modules
      - /code/bower_components
