# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_added_team_model")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bg-images"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
