# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_added_description_and_background_image_to_team_model")
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="email",
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="github_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="personal_website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
