# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 20:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_added_backgound_image_to_team_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
