# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0004_change_team_model_field_type")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="visible",
            field=models.BooleanField(default=False),
        )
    ]
