# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0006_add_status_field_in_contact_model")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="position",
            field=models.PositiveIntegerField(default=0),
        )
    ]
