# -*- coding: utf-8 -*-
# Generated by Django 2.2.20 on 2026-01-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("web", "0010_add_verbose_name_plural_for_subscribers_model")]

    operations = [
        migrations.AlterField(
            model_name="subscribers",
            name="email",
            field=models.EmailField(max_length=70, unique=True),
        )
    ]

