# Generated by Django 2.2.20 on 2023-04-15 08:18

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_add_verbose_name_plural_for_subscribers_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[web.models.validate_github_url]),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[web.models.validate_linkedin_url]),
        ),
    ]
