from django.urls import re_path

from . import views

app_name = "jobs"

urlpatterns = [
    re_path(
        r"^challenge/(?P<challenge_pk>[0-9]+)/"
        r"challenge_phase/(?P<challenge_phase_pk>[0-9]+)/"
        r"submission/(?P<submission_pk>[0-9]+)$",
        views.change_submission_data_and_visibility,
        name="change_submission_data_and_visibility",
    ),
    re_path(
        r"^challenge/(?P<challenge_id>[0-9]+)/"
        r"challenge_phase/(?P<challenge_phase_id>[0-9]+)/"
        r"submission/$",
        views.challenge_submission,
        name="challenge_submission",
    ),
    re_path(
        r"^(?P<challenge_pk>[0-9]+)/remaining_submissions/$",
        views.get_remaining_submissions,
        name="get_remaining_submissions",
    ),
    re_path(
        r"^submissions/(?P<submission_pk>[0-9]+)/re-run/$",
        views.re_run_submission,
        name="re_run_submission",
    ),
    re_path(
        r"^submissions/(?P<submission_pk>[0-9]+)/resume/$",
        views.resume_submission,
        name="resume_submission",
    ),
    re_path(
        r"^challenge_phase_split/(?P<challenge_phase_split_id>[0-9]+)/"
        r"leaderboard/$",
        views.leaderboard,
        name="leaderboard",
    ),
    re_path(
        r"^phase_split/(?P<challenge_phase_split_pk>[0-9]+)/"
        r"public_leaderboard_all_entries/$",
        views.get_all_entries_on_public_leaderboard,
        name="get_all_entries_on_public_leaderboard",
    ),
    re_path(
        r"^submission/(?P<submission_id>[0-9]+)$",
        views.get_submission_by_pk,
        name="get_submission_by_pk",
    ),
    re_path(
        r"^challenge/(?P<challenge_pk>[0-9]+)/update_submission/$",
        views.update_submission,
        name="update_submission",
    ),
    re_path(
        r"^challenges/(?P<challenge_pk>[0-9]+)/"
        r"update_partially_evaluated_submission/$",
        views.update_partially_evaluated_submission,
        name="update_partially_evaluated_submission",
    ),
    re_path(
        r"^challenge/(?P<challenge_pk>[0-9]+)/submission/$",
        views.get_submissions_for_challenge,
        name="get_submissions_for_challenge",
    ),
    re_path(
        r"^queues/(?P<queue_name>[\w-]+)/$",
        views.delete_submission_message_from_queue,
        name="delete_submission_message_from_queue",
    ),
    re_path(
        r"^challenge/queues/(?P<queue_name>[\w-]+)/$",
        views.get_submission_message_from_queue,
        name="get_submission_message_from_queue",
    ),
    re_path(
        r"^submission_files/$",
        views.get_signed_url_for_submission_related_file,
        name="get_signed_url_for_submission_related_file",
    ),
    re_path(
        r"^leaderboard_data/(?P<leaderboard_data_pk>[0-9]+)/$",
        views.update_leaderboard_data,
        name="update_leaderboard_data",
    ),
    re_path(
        r"^challenge/(?P<challenge_pk>[0-9]+)/eks_bearer_token/$",
        views.get_bearer_token,
        name="get_bearer_token",
    ),
    re_path(
        r"^phase_splits/(?P<challenge_phase_split_pk>[0-9]+)/"
        r"teams/(?P<participant_team_pk>[0-9]+)/github_badge/$",
        views.get_github_badge_data,
        name="get_github_badge_data",
    ),
    re_path(
        r"^phases/(?P<challenge_phase_pk>[0-9]+)/"
        r"send_submission_message/(?P<submission_pk>[0-9]+)/$",
        views.send_submission_message,
        name="send_submission_message",
    ),
    re_path(
        r"^phases/(?P<challenge_phase_pk>[0-9]+)/"
        r"submission_count_by_status/$",
        views.challenge_phase_submission_count_by_status,
        name="challenge_phase_submissions_by_status",
    ),
    re_path(
        r"^phases/(?P<challenge_phase_pk>[0-9]+)/"
        r"get_submission_file_presigned_url/$",
        views.get_submission_file_presigned_url,
        name="get_submission_file_presigned_url",
    ),
    re_path(
        r"^phases/(?P<challenge_phase_pk>[0-9]+)/"
        r"finish_submission_file_upload/(?P<submission_pk>[0-9]+)/$",
        views.finish_submission_file_upload,
        name="finish_submission_file_upload",
    ),
    re_path(
        r"^submission/(?P<submission_pk>[0-9]+)/update_started_at/$",
        views.update_submission_started_at,
        name="update_submission_started_at",
    ),
    re_path(
        r"^challenges/(?P<challenge_pk>[0-9]+)/"
        r"submissions/(?P<submission_pk>[0-9]+)/update_submission_meta/$",
        views.update_submission_meta,
        name="update_submission_meta",
    ),
]
