# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration',
            field=models.TimeField(default=datetime.timedelta(0, 300)),
        ),
    ]
