# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0002_path_fix_for_submission_files")]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="method_name",
            field=models.CharField(max_length=1000, null=True),
        )
    ]
