# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_submission_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='duration',
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time_limit',
            field=models.PositiveIntegerField(default=datetime.timedelta(0, 300)),
        ),
    ]
