# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_submitting_status_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
