# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_added_method_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
