# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0003_added_method_name_field")]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="method_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="project_url",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="publication_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
