# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 17:16
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_submission_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='input_file',
            field=models.FileField(upload_to=base.utils.RandomFileName('submission_files/submission')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='stderr_file',
            field=models.FileField(blank=True, null=True, upload_to=base.utils.RandomFileName('submission_files/submission')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='stdout_file',
            field=models.FileField(blank=True, null=True, upload_to=base.utils.RandomFileName('submission_files/submission')),
        ),
    ]
