# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-04 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0009_auto_20180629_0334")]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="method_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="project_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="submission",
            name="publication_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
