# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0037_add_field_to_store_forum_url'),
        ('jobs', '0010_Add_blank_in_submission_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='challenge_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.Challenge'),
            preserve_default=False,
        ),
    ]
