# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_Add_blank_in_submission_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='baseline_submission',
            field=models.BooleanField(default=False),
        ),
    ]
