# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0010_Add_blank_in_submission_metadata")]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="is_public",
            field=models.BooleanField(default=True),
        )
    ]
