# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_Change_submission_visibility_default_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
    ]
