# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-20 04:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0012_add_baseline_submission")]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="job_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        )
    ]
