# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-20 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("jobs", "0013_add_job_id_field_in_submission_model")]

    operations = [
        migrations.RenameField(
            model_name="submission", old_name="job_id", new_name="job_name"
        )
    ]
