# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-14 15:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_archived_as_a_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_meta_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
