# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 08:46
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_archived_as_a_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('input_file', models.FileField(upload_to=base.utils.RandomFileName('submission_files/submission_{id}'))),
            ],
            options={
                'db_table': 'submissionfile',
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='input_file',
        ),
    ]
