# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-27 10:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_add_ignore_submission_boolean_field_in_submission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_meta_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
