# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-30 06:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobs",
            "0016_add_ignore_submission_boolean_field_in_submission_model",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submission_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "submitted"),
                    ("running", "running"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("finished", "finished"),
                    ("submitting", "submitting"),
                    ("archived", "archived"),
                    ("partially_evaluated", "partially_evaluated"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
