# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-06 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_add_submission_metadata_field_to_submission")
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="input_file_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        )
    ]
