# Generated by Django 2.2.8 on 2020-11-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_add_field_to_store_input_file_url_for_large_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='challenge_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='challenges.ChallengePhase'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='participants.ParticipantTeam'),
        ),
    ]
