# Generated by Django 2.2.13 on 2021-02-03 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_add_field_to_store_input_file_url_for_large_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='job_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
