# Generated by Django 2.2.13 on 2021-05-25 20:10

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_add_missing_migration_file_after_django_2_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="docker_input_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.RandomFileName(
                    "submission_files/submission_{id}"
                ),
            ),
        ),
    ]
