# Generated by Django 2.2.20 on 2022-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_add_submission_verified_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_baseline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
