# Generated by Django 2.2.20 on 2022-10-25 21:22

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_submission_enverr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='static_code_upload_environment_log_file',
            field=models.FileField(blank=True, null=True, upload_to=base.utils.RandomFileName('submission_files/submission_{id}')),
        ),
    ]
