# Generated by Django 2.2.20 on 2022-11-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_submission_static_code_upload_submission_log_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='static_code_upload_environment_log_file',
        ),
    ]
