# Generated by Django 2.2.20 on 2025-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0026_auto_20230804_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="artifact_deletion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when submission artifacts were deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_artifact_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating whether submission artifacts have been deleted",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="retention_eligible_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date when submission artifacts become eligible for deletion",
                null=True,
            ),
        ),
    ]
