# Generated by Django 2.2.20 on 2024-04-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20230804_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='from_cli',
            field=models.BooleanField(default=False),
        ),
    ]
