# Generated by Django on 2024-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0026_auto_20230804_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_cli",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
