# Generated by Django 2.2.20 on 2025-07-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0027_add_retention_policy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="retention_override_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for any retention policy override applied to this submission",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="retention_policy_applied",
            field=models.CharField(
                blank=True,
                help_text="Description of retention policy applied to this submission",
                max_length=100,
                null=True,
            ),
        ),
    ]
