# Generated by Cursor on 2026-05-16

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0027_add_composite_indexes_to_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="environment_log_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="input_file",
            field=models.FileField(
                upload_to=base.utils.SubmissionArtifactFileName()
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="stderr_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="stdout_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_input_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_metadata_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_result_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.SubmissionArtifactFileName(),
            ),
        ),
    ]
