# Generated by Django 2.2.20 on 2026-01-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # TODO: Is this dependency needed for this app?
    dependencies = [
        ('challenges', '0113_add_github_branch_field_and_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('free', 'Free'), ('essentials', 'Essentials'), ('core', 'Core'), ('advanced', 'Advanced'), ('remote', 'Remote')], db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'payment_tier',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChallengePaymentTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tier_mapping', to='challenges.Challenge')),
                ('payment_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_mappings', to='payments.PaymentTier')),
            ],
            options={
                'db_table': 'challenge_payment_tier',
            },
        ),
    ]
