# Generated by Django 2.2.20 on 2022-10-31 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('challenges', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboarddata',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Submission'),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='challenge_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.ChallengePhase'),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='dataset_split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.DatasetSplit'),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Leaderboard'),
        ),
        migrations.AddField(
            model_name='challengephase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
        migrations.AddField(
            model_name='challengephase',
            name='dataset_split',
            field=models.ManyToManyField(blank=True, through='challenges.ChallengePhaseSplit', to='challenges.DatasetSplit'),
        ),
        migrations.AddField(
            model_name='challengeevaluationcluster',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
        migrations.AddField(
            model_name='challengeconfiguration',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
        migrations.AddField(
            model_name='challengeconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_creator', to='hosts.ChallengeHostTeam'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='participant_teams',
            field=models.ManyToManyField(blank=True, to='participants.ParticipantTeam'),
        ),
        migrations.AlterUniqueTogether(
            name='challengephase',
            unique_together={('codename', 'challenge')},
        ),
    ]
