# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0002_challenge_participant_teams")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="participant_teams",
            field=models.ManyToManyField(
                blank=True, to="participants.ParticipantTeam"
            ),
        )
    ]
