# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0003_auto_20161203_2258")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_disabled",
            field=models.BooleanField(default=False),
        )
    ]
