# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("challenges", "0006_changed_path_to_upload")]

    operations = [
        migrations.RenameModel(
            old_name="TestEnvironment", new_name="ChallengePhase"
        ),
        migrations.AlterModelTable(
            name="challengephase", table="challenge_phase"
        ),
    ]
