# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0008_max_submissions")]

    operations = [
        migrations.AddField(
            model_name="challengephase",
            name="is_public",
            field=models.BooleanField(default=False),
        )
    ]
