# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challengephase_is_public'),
        ('challenges', '0009_update_upload_folder_names'),
    ]

    operations = [
    ]
