# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0010_update_upload_folder_names")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="approved_by_admin",
            field=models.BooleanField(
                default=False, verbose_name="Approved By Admin"
            ),
        )
    ]
