# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_merge_20170108_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengephase',
            name='test_annotation',
            field=models.FileField(upload_to='testAnnotations'),
        ),
    ]
