# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("challenges", "0013_added_code_name_field")]

    operations = [
        migrations.RenameField(
            model_name="challengephase",
            old_name="code_name",
            new_name="codename",
        ),
        migrations.AlterUniqueTogether(
            name="challengephase",
            unique_together=set([("codename", "challenge")]),
        ),
    ]
