# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0024_added_short_description_field")]

    operations = [
        migrations.AddField(
            model_name="challengephase",
            name="is_submission_public",
            field=models.BooleanField(default=False),
        )
    ]
