# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0026_adds_default_field_in_test_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsplit',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
