# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-22 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0028_zip_configuration_models_for_challenge_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengePhaseDescriptionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description_file', models.FileField(blank=True, null=True, upload_to='challenge_description_file')),
                ('challenge_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.ChallengePhase')),
            ],
            options={
                'db_table': 'challenge_phase_description_file',
            },
        ),
    ]
