# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0029_add_challenge_star")]

    operations = [
        migrations.AddField(
            model_name="starchallenge",
            name="is_starred",
            field=models.BooleanField(default=False),
        )
    ]
