# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0032_adds_featured_field_in_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsplit',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='challengephase',
            unique_together=set([('id', 'codename'), ('id', 'dataset_split')]),
        ),
    ]
