# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-01 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0032_adds_featured_field_in_challenge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengephasesplit',
            unique_together=set([('challenge_phase', 'dataset_split')]),
        ),
    ]
