# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0035_phase_id_field_for_challenge_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephasesplit',
            name='phase_split_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
