# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-12 11:03
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0035_add_max_concurrent_submissions_allowed_field")
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.utils.RandomFileName("logos"),
                verbose_name="Logo",
            ),
        )
    ]
