# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0036_Add_unique_random_name_to_challenge_logo")
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="forum_url",
            field=models.URLField(blank=True, max_length=100, null=True),
        )
    ]
