# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-03 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0036_phase_split_id_field_for_challenge_phase_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephasesplit',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
