# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0037_add_field_to_store_forum_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='max_submissions_per_month',
            field=models.PositiveIntegerField(db_index=True, default=100000),
        ),
    ]
