# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_challengephase_max_submissions_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengephase',
            name='max_submissions_per_month',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
