# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0039_add_sqs_broker_url_for_challenge_based_worker")
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge", old_name="broker_url", new_name="queue"
        )
    ]
