# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0039_auto_20181028_1819'),
        ('challenges', '0038_challenge_remote_evaluation'),
    ]

    operations = [
    ]
