# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0039_challengephase_max_submissions_per_month'),
        ('challenges', '0040_change_broker_url_name_to_queue'),
    ]

    operations = [
    ]
