# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0041_add_challenge_phase_max_submissions_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_docker_based',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Docker Based'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
