# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0041_add_challenge_phase_max_submissions_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='leaderboard_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
