# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 23:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0043_add_max_docker_image_size_for_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='allowed_email_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
