# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0043_add_max_docker_image_size_for_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allowed_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=['.zip', '.json'], size=None),
        ),
    ]
