# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0047_add_model_to_invite_user_in_challenge")
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="aws_account_id",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="aws_region",
            field=models.CharField(
                blank=True, default="us-east-1", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="aws_secret_access_key",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="use_host_credentials",
            field=models.BooleanField(default=False),
        ),
    ]
