# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 22:48
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0051_add_field_to_store_evalai_cli_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDescriptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.utils.RandomFileName('description_image'), verbose_name='Description Image')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
        ),
    ]
