# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 20:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0051_add_field_to_store_evalai_cli_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboarddata",
            name="error",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True
            ),
        ),
    ]
