# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0052_add_error_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
