# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 18:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0053_added_is_registration_open_field")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="banned_email_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        )
    ]
