# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_add_task_def_arn_and_worker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='task_def_arn',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
