# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_add_banned_email_ids_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='leaderboard_order_is_descending',
            field=models.BooleanField(default=True),
        ),
    ]
