# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-14 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_add_banned_email_ids_field'),
        ('challenges', '0055_changed_task_def_arn_field'),
    ]

    operations = [
    ]
