# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0056_add_leaderboard_decimal_precision_field_in_phase_split_model'),
        ('challenges', '0056_merge_20190714_1356'),
    ]

    operations = [
    ]
