# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0056_add_leaderboard_decimal_precision_field_in_phase_split_model",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="task_def_arn",
            field=models.CharField(
                blank=True, default="", max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="workers",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
