# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_add_task_def_arn_and_workers_field_to_challenge_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='task_def_arn',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
