# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_add_task_def_arn_and_workers_field_to_challenge_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='private_annotations',
            field=models.BooleanField(default=False),
        ),
    ]
