# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 10:24
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_add_task_def_arn_and_workers_field_to_challenge_model.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='custom_requirements',
            field=models.FileField(default=False, upload_to=base.utils.RandomFileName('custom_requirements')),
        ),
    ]
