# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_add_task_def_arn_and_workers_field_to_challenge_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='environment_url',
            field=models.CharField(max_length=2128, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
