# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 13:04
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0058_add_private_annotation_field_to_Challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengephase',
            name='test_annotation',
            field=models.FileField(blank=True, default=False, null=True, upload_to=base.utils.RandomFileName('test_annotations')),
        ),
    ]
