# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-24 17:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0058_adding_environment_url_for_rl_challenges")
    ]

    operations = [
        migrations.AlterField(
            model_name="challengephase",
            name="environment_url",
            field=models.CharField(
                blank=True,
                max_length=2128,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        )
    ]
