# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-18 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0059_add_blank_in_phase_environment_url")]

    operations = [
        migrations.RemoveField(
            model_name="challengephase", name="environment_url"
        ),
        migrations.AddField(
            model_name="challengephase",
            name="environment_image",
            field=models.CharField(blank=True, max_length=2128, null=True),
        ),
    ]
