# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-16 21:33
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0059_add_blank_in_phase_environment_url")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="evaluation_cluster_config",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.RandomFileName(
                    "evaluation_cluster_config"
                ),
            ),
        )
    ]
