# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_add_models_to_store_kubernetes_cluster_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slack_webhook_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
