# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-30 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_add_models_to_store_kubernetes_cluster_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], size=None),
        ),
    ]
