# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0061_add_models_to_store_kubernetes_cluster_details")
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboarddata",
            name="is_active",
            field=models.BooleanField(default=True),
        )
    ]
