# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0062_add_allowed_submission_file_types_field_in_phase_model",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="slack_webhook_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
