# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0064_add_is_restricted_to_select_one_submission_field_in_phase_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='last_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
