# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-28 04:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_add_cluster_details_to_challenge_evaluation_cluster_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='submission_meta_attributes_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
