# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_add_cluster_details_to_challenge_evaluation_cluster_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='worker_last_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
