# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-30 05:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0066_added_is_partial_submission_evaluation_enabled_field_in_phase_model",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="challengephase",
            name="submission_meta_attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        )
    ]
