# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-30 13:36
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0067_add_submission_meta_attribute_field_to_challenge_phase",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="challengephase",
            name="test_annotation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=base.utils.RandomFileName("test_annotations"),
            ),
        )
    ]
