# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0068_change_test_annotation_to_be_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='challenge_phase_prioritize',
            field=models.BooleanField(default=False),
        ),
    ]
