# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0071_add_challenge_template_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='worker_cpu_cores',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='worker_memory',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
