# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0072_add_fargate_worker_cpu_and_memory_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='inform_hosts',
            field=models.BooleanField(default=True),
        ),
    ]
