# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-17 23:49
from __future__ import unicode_literals

import challenges.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0074_add_default_meta_attributes_field")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="allowed_email_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="banned_email_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="blocked_email_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challengephase",
            name="allowed_email_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challengetemplate",
            name="eval_metrics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200),
                blank=True,
                default=challenges.models.get_default_eval_metric,
                size=None,
            ),
        ),
    ]
