# Generated by Django 2.2.8 on 2020-11-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0074_add_default_meta_attributes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_creator', to='hosts.ChallengeHostTeam'),
        ),
        migrations.AlterField(
            model_name='challengeconfiguration',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='challengeconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengeevaluationcluster',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='challengephase',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='challengephasesplit',
            name='challenge_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.ChallengePhase'),
        ),
        migrations.AlterField(
            model_name='challengephasesplit',
            name='dataset_split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.DatasetSplit'),
        ),
        migrations.AlterField(
            model_name='challengephasesplit',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='leaderboarddata',
            name='challenge_phase_split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.ChallengePhaseSplit'),
        ),
        migrations.AlterField(
            model_name='leaderboarddata',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='leaderboarddata',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.Submission'),
        ),
        migrations.AlterField(
            model_name='starchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='starchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge', to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hosts.ChallengeHost'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
