# Generated by Django 2.2.13 on 2020-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0076_add_one_to_one_models_to_map_challenges_with_pwc_task_dataset",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="pwcchallengeleaderboard",
            name="enable_sync",
            field=models.BooleanField(
                db_index=True,
                default=True,
                verbose_name="Enable leaderboard sync to PWC",
            ),
        ),
        migrations.AlterField(
            model_name="pwcchallengeleaderboard",
            name="area",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="pwcchallengeleaderboard",
            name="dataset",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="pwcchallengeleaderboard",
            name="task",
            field=models.CharField(db_index=True, default="", max_length=200),
        ),
    ]
