# Generated by Django 2.2.13 on 2021-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0077_add_boolean_field_to_enable_sync_and_make_other_fields_required_in_pwc_challenge_leaderboard_models",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="ecr_all_access_policy_arn",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="eks_arn_role",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="internet_gateway_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="node_group_arn_role",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="route_table_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="security_group_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="subnet_1_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="subnet_2_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="vpc_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
