# Generated by Django 2.2.13 on 2021-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0078_add_cluster_network_and_arn_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="subnet_1_cidr",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="subnet_2_cidr",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="vpc_cidr",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
    ]
