# Generated by Django 2.2.13 on 2021-02-21 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0079_add_code_upload_setup_vpc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
