# Generated by Django 2.2.13 on 2021-02-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0080_challenge_challenge_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_type',
        ),
    ]
