# Generated by Django 2.2.13 on 2021-03-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0080_add_code_upload_cluster_instance_config"),
        ("challenges", "0080_auto_20210209_1718"),
    ]

    operations = []
