# Generated by Django 2.2.13 on 2021-03-01 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0080_add_code_upload_cluster_instance_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="efs_creation_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="efs_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="efs_mount_target_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=256),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="challengeevaluationcluster",
            name="efs_security_group_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
