# Generated by Django 2.2.13 on 2021-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0082_challengephasesplit_show_execution_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengephase",
            name="annotations_uploaded_using_cli",
            field=models.BooleanField(default=False),
        ),
    ]
