# Generated by Django 2.2.13 on 2021-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0082_challengephasesplit_show_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
