# Generated by Django 2.2.13 on 2021-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0084_challenge_is_static_dataset_code_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_multi_metric_leaderboard",
            field=models.BooleanField(default=False),
        ),
    ]
