# Generated by Django 2.2.13 on 2021-03-06 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0084_challenge_is_static_dataset_code_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
