# Generated by Django 2.2.20 on 2021-08-11 06:51

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0085_challenge_submission_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='requirements',
            field=models.FileField(blank=True, upload_to=base.utils.RandomFileName('requirements')),
        ),
    ]
