# Generated by Django 2.2.20 on 2021-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0085_challenge_submission_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengephasesplit",
            name="is_multi_metric_leaderboard",
            field=models.BooleanField(default=True),
        ),
    ]
