# Generated by Django 2.2.20 on 2021-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0085_challenge_submission_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="github_token",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
    ]
