# Generated by Django 2.2.20 on 2021-08-11 08:25

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_challenge_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=models.FileField(blank=True, null=True, upload_to=base.utils.RandomFileName('requirements')),
        ),
    ]
