# Generated by Django 2.2.20 on 2022-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_add_is_multi_metric_leaderboard_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='cpu_only_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='job_cpu_cores',
            field=models.CharField(blank=True, default='2000m', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='job_memory',
            field=models.CharField(blank=True, default='8Gi', max_length=256, null=True),
        ),
    ]
