# Generated by Django 2.2.20 on 2021-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_add_is_multi_metric_leaderboard_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
