# Generated by Django 2.2.20 on 2021-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0086_add_is_multi_metric_leaderboard_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="github_token",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
    ]
