# Generated by Django 2.2.20 on 2022-05-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_add_is_multi_metric_leaderboard_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_users_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
