# Generated by Django 2.2.20 on 2021-08-11 08:33

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0087_auto_20210811_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=models.FileField(default=False, upload_to=base.utils.RandomFileName('requirements')),
        ),
    ]
