# Generated by Django 2.2.20 on 2023-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0088_increase_cpu_workers_and_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CV", "Computer Vision"),
                    ("NLP", "Natural Language Processing"),
                    ("RL", "Reinforcement Learning"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
