# Generated by Django 2.2.20 on 2023-03-24 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], size=None),
        ),
    ]
