# Generated by Django 2.2.20 on 2023-05-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='use_host_sqs',
            field=models.BooleanField(default=False),
        ),
    ]
