# Generated by Django 2.2.20 on 2022-10-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
        ('challenges', '0088_add_environment_error_entry'),
    ]

    operations = [
    ]
