# Generated by Django 2.2.20 on 2023-03-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='has_prizes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChallengePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
            options={
                'db_table': 'challenge_prize',
            },
        ),
    ]
