# Generated by Django 2.2.20 on 2023-06-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='domain',
            field=models.CharField(blank=True, choices=[('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('RL', 'Reinforcement Learning')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChallengeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=200)),
                ('challenge', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
            options={
                'db_table': 'challenge_tags',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='list_tags',
            field=models.ManyToManyField(blank=True, related_name='challenge_tags', to='challenges.ChallengeTags'),
        ),
    ]
