# Generated by Django 2.2.20 on 2023-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Paper', 'Paper'), ('Dataset', 'Dataset'), ('Environment', 'Environment'), ('Workshop', 'Workshop')], db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'challenge_tags',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='list_tags',
            field=models.ManyToManyField(blank=True, to='challenges.ChallengeTags'),
        ),
    ]
