# Generated by Django 2.2.20 on 2023-05-19 08:27

import base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_increase_cpu_workers_and_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'challenge_tags',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='domain',
            field=models.CharField(blank=True, choices=[('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('RL', 'Reinforcement Learning')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_sponsors',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChallengeSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sponsor_logo', models.ImageField(blank=True, null=True, upload_to=base.utils.RandomFileName('sponsor_logo'), verbose_name='Sponsor Logo')),
                ('sponsor', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor_url', models.URLField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sponsor', to='challenges.Challenge')),
            ],
            options={
                'db_table': 'challenge_sponsor',
            },
        ),
        migrations.CreateModel(
            name='ChallengePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
            options={
                'db_table': 'challenge_prize',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='list_tags',
            field=models.ManyToManyField(blank=True, to='challenges.ChallengeTags'),
        ),
    ]
