# Generated by Django 2.2.20 on 2023-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0089_auto_20230519_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetags',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challengetags',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='challengetags',
            name='tag_name',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Dataset', 'Dataset'), ('Environment', 'Environment'), ('Workshop', 'Workshop')], db_index=True, max_length=200),
        ),
    ]
