# Generated by Django 2.2.20 on 2021-08-13 02:45

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0089_auto_20210811_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=models.FileField(blank=True, default='', upload_to=base.utils.RandomFileName('requirements')),
        ),
    ]
