# Generated by Django 2.2.20 on 2021-09-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0090_auto_20210813_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='requirements',
        ),
    ]
