# Generated by Django 2.2.20 on 2023-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0090_challenge_allow_resuming_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='approval_requested',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Approved By Admin'),
        ),
    ]
