# Generated by Django 2.2.20 on 2023-05-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0090_auto_20230519_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesponsor',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
