# Generated by Django 2.2.20 on 2023-06-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0091_challenge_allow_host_cancel_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allow_cancel_running_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
