# Generated by Django 2.2.20 on 2023-06-14 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0092_challenge_allow_cancel_running_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='domain',
            field=models.CharField(blank=True, choices=[('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('RL', 'Reinforcement Learning')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='list_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], size=None),
        ),
    ]
