# Generated by Django 2.2.20 on 2023-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0093_manual_participant_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allow_participants_resubmissions',
            field=models.BooleanField(default=False),
        ),
    ]
