# Generated by Django 2.2.20 on 2023-06-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0094_challenge_allow_participants_resubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='queue_aws_region',
            field=models.CharField(blank=True, default='us-east-1', max_length=50, null=True),
        ),
    ]
