# Generated by Django 2.2.20 on 2023-07-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0097_challengephase_disable_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='leaderboard_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
