# Generated by Django 2.2.20 on 2023-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0098_challenge_tags_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
