# Generated by Django 2.2.20 on 2023-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0099_challenge_worker_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='uses_ec2_worker',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uses separate EC2 worker instance'),
        ),
    ]
