# Generated by Django 2.2.20 on 2023-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0101_challenge_ec2_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ec2_storage',
            field=models.PositiveIntegerField(default=8, verbose_name='EC2 storage (GB)'),
        ),
    ]
