# Generated by Django 2.2.20 on 2023-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0103_challenge_worker_image_url_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='sqs_retention_time',
            field=models.IntegerField(blank=True, default=1209600, null=True),
        ),
    ]
