# Generated by Django 2.2.20 on 2023-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0104_challenge_evaluation_module_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='exact_match',
            field=models.BooleanField(default=False),
        ),
    ]
