# Generated by Django 2.2.20 on 2023-10-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0105_challenge_sponsors_prizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='worker_image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
