# Generated by Django 2.2.20 on 2023-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0105_challenge_sponsors_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='worker_image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
