# Generated by Django 2.2.20 on 2023-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0106_challenge_worker_image_url_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
