# Generated by Django 2.2.20 on 2023-10-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0106_challenge_worker_image_url_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ephemeral_storage',
            field=models.PositiveIntegerField(default=20, verbose_name='Ephemeral Storage (GB)'),
        ),
    ]
