# Generated by Django 2.2.20 on 2023-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0106_challenge_github_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='exact_match',
            field=models.BooleanField(default=False),
        ),
    ]
