# Generated by Django 2.2.20 on 2023-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0109_alter_leaderboarddata_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ephemeral_storage',
            field=models.PositiveIntegerField(default=20, verbose_name='Ephemeral Storage (GB)'),
        ),
    ]
