# Generated by Django 2.2.20 on 2023-11-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0109_alter_leaderboarddata_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengephasesplit',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
