# Generated by Django 2.2.20 on 2023-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0111_alter_challenge_ephemeral_storage_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='sqs_retention_period',
            field=models.PositiveIntegerField(default=259200, verbose_name='SQS Retention Period'),
        ),
    ]
