# Generated by Django 2.2.20 on 2024-03-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0112_challenge_sqs_retention_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submission_must_finish_before_end',
            field=models.BooleanField(default=False),
        ),
    ]
