# Generated by Django 2.2.20 on 2025-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0112_challenge_sqs_retention_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="github_branch",
            field=models.CharField(
                blank=True, default="challenge", max_length=200, null=True
            ),
        ),
        # Add a partial unique constraint that only applies when both fields are not empty
        migrations.RunSQL(
            "CREATE UNIQUE INDEX challenge_github_repo_branch_partial_idx ON challenge (github_repository, github_branch) WHERE github_repository != '' AND github_branch != '';",
            reverse_sql="DROP INDEX IF EXISTS challenge_github_repo_branch_partial_idx;",
        ),
    ]
