# Generated by Django 2.2.20 on 2024-08-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0112_challenge_sqs_retention_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="disable_private_submission",
            field=models.BooleanField(default=False),
        ),
    ]
