# Generated by Django 2.2.20 on 2025-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0112_challenge_sqs_retention_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='github_branch',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
