# Generated by Django 2.2.20 on 2025-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0112_challenge_sqs_retention_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="sqs_visibility_timeout",
            field=models.PositiveIntegerField(
                default=300, verbose_name="SQS Visibility Timeout"
            ),
        ),
    ]
