# Generated by Django 2.2.20 on 2025-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0113_add_github_branch_field_and_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="github_token",
            field=models.CharField(
                max_length=500,
                null=True,
                blank=True,
                default="",
            ),
        ),
    ]
