# Generated by Django 2.2.20 on 2026-01-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0113_add_github_branch_field_and_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='payment_tier',
            field=models.CharField(choices=[('free', 'Free'), ('essentials', 'Essentials'), ('core', 'Core'), ('advanced', 'Advanced'), ('remote', 'Remote')], default='free', max_length=50),
        ),
    ]
