# Generated by Django 2.2.20 on 2026-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0113_add_github_branch_field_and_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="require_complete_profile",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, participants must have a complete "
                "profile (name, address, city, state, country) before "
                "joining this challenge.",
                verbose_name="Require Complete Profile",
            ),
        ),
    ]
