# Generated by Django 2.2.20 on 2025-07-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0113_add_github_branch_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('github_repository', 'github_branch')},
        ),
    ]
