# Generated by Django 2.2.20 on 2026-02-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0114_add_require_complete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengephasesplit",
            name="show_scores_on_leaderboard",
            field=models.BooleanField(default=True),
        ),
    ]
