# Generated by Django 2.2.20 on 2025-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0114_add_github_token_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='last_github_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
