# Generated by Django 2.2.20 on 2025-07-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0114_add_log_retention_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="retention_policy_consent",
            field=models.BooleanField(
                default=False,
                help_text="Challenge host has consented to allow to set a 30-day retention policy for this challenge",
                verbose_name="Retention Policy Consent",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="retention_policy_consent_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who provided retention policy consent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retention_consent_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="retention_policy_consent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when retention policy consent was given",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="retention_policy_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about retention policy for this challenge",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="log_retention_days_override",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Admin override for CloudWatch log retention period in days (defaults to 30 days when host has consented)",
                null=True,
            ),
        ),
    ]
