# Generated by Django 2.2.20 on 2026-02-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0115_add_show_scores_on_leaderboard_to_challenge_phase_split",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leaderboarddata",
            index=models.Index(
                fields=["challenge_phase_split", "is_disabled", "-created_at"],
                name="ld_chphase_isdisc_created_idx",
            ),
        ),
    ]
