# Generated by Django 2.2.20 on 2026-02-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0116_leaderboard_data_leaderboard_query_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_frozen",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When frozen, challenge hosts cannot modify the start and end dates. Automatically set to True when a challenge is approved by admin.",
                verbose_name="Is Frozen",
            ),
        ),
    ]
