# Generated by Django 2.2.20 on 2026-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0117_add_challenge_is_frozen_field_to_prevent_hosts_changing_start_end_dates",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_approval_requested",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set to True once a challenge host submits an approval request. Prevents duplicate subscription plan emails from being sent.",
                verbose_name="Is Approval Requested",
            ),
        ),
    ]
