# Generated by Django 2.2.20 on 2026-02-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0117_add_challenge_is_frozen_field_to_prevent_hosts_changing_start_end_dates",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="sqs_visibility_timeout",
            field=models.PositiveIntegerField(
                default=300, verbose_name="SQS Visibility Timeout"
            ),
        ),
    ]
