# Generated by Django 2.2.20 on 2026-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0118_add_is_approval_requested_to_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_submission_paused",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, new submissions are rejected for all phases of this challenge. Already-queued submissions continue processing normally.",
                verbose_name="Submissions Paused",
            ),
        ),
        migrations.AddField(
            model_name="challengephase",
            name="is_submission_paused",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, new submissions are rejected for this phase. Already-queued submissions continue processing normally.",
                verbose_name="Submissions Paused",
            ),
        ),
    ]
