# Generated by Django 2.2.20 on 2026-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0120_remove_duplicate_star_challenges_and_add_unique_constraint",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="fargate_base",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum number of tasks placed on FARGATE before weights apply.",
                verbose_name="Fargate Base",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="fargate_spot_base",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum number of tasks placed on FARGATE_SPOT before weights apply.",
                verbose_name="Fargate Spot Base",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="fargate_spot_weight",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Weight for FARGATE_SPOT in capacity provider strategy. 0 excludes Spot.",
                verbose_name="Fargate Spot Weight",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="fargate_weight",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Weight for FARGATE in capacity provider strategy. 0 = Spot only.",
                verbose_name="Fargate Weight",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="use_fargate_spot",
            field=models.BooleanField(
                default=True,
                help_text="If True, use capacityProviderStrategy (Spot). If False, use launchType FARGATE.",
                verbose_name="Use Fargate Spot",
            ),
        ),
    ]
