# Generated by Cursor on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0121_add_fargate_spot_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenge_usage_type",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("internal", "Internal"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challengephase",
            name="submission_artifact_retention_policy",
            field=models.CharField(
                choices=[
                    ("keep_forever", "Keep forever"),
                    ("days_14", "14 days"),
                    ("days_30", "30 days"),
                    ("months_3", "3 months"),
                    ("months_6", "6 months"),
                    ("months_12", "12 months"),
                ],
                db_index=True,
                default="keep_forever",
                max_length=20,
            ),
        ),
    ]
