# Generated by Django 2.2.20 on 2026-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0123_update_challenge_usage_type_default_and_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_team_members",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of members allowed per participant "
                "team. Leave blank for no limit.",
                null=True,
                verbose_name="Maximum Team Members",
            ),
        ),
    ]
