# Generated by Django 2.2.20 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0127_alter_challenge_worker_python_version_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="submission_queue_time_limit",
            field=models.PositiveIntegerField(
                default=7200,
                help_text=(
                    "Maximum seconds a submission may remain in a pre-running "
                    "queue state (submitted, submitting, queued, resuming) "
                    "before it is automatically marked failed. Set to 0 to "
                    "disable."
                ),
            ),
        ),
    ]
