# Generated by Django 2.2.20 on 2026-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0127_alter_challenge_worker_python_version_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_ecs_workers",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="min_ecs_workers",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
