# Generated by Django 2.2.20 on 2026-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0128_challenge_max_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="max_ecs_workers",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Autoscaling ceiling: max workers the scale-up policy can launch when the SQS queue is non-empty.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="min_ecs_workers",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Autoscaling floor: min workers kept alive when the SQS queue is empty. 0 allows scale-to-zero.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="workers",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="ECS service lifecycle state: None = never started, 0 = stopped, N = running N workers.",
                null=True,
            ),
        ),
    ]
