# Generated by Django 2.2.20 on 2026-07-30 05:00
# pylint: disable=line-too-long,duplicate-code

import base.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0129_add_ecs_worker_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="allow_cancel_running_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Let hosts cancel a submission that has already started running.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="allow_host_cancel_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Let hosts cancel a participant's queued submission.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="allow_participants_resubmissions",
            field=models.BooleanField(
                default=False,
                help_text="Let participants resubmit without consuming a new attempt.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="allow_resuming_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Let hosts re-queue a failed or cancelled submission.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="allowed_email_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                help_text="If non-empty, only these email domains may join, e.g. example.com.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="anonymous_leaderboard",
            field=models.BooleanField(
                default=False,
                help_text="Hide participant team names on the public leaderboard.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="approved_by_admin",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="EvalAI admin approval. Provisions workers or the EKS cluster the first time it is set.",
                verbose_name="Approved By Admin",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="approved_participant_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teams cleared to submit when manual participant approval is enabled.",
                related_name="approved_challenge_participant_teams",
                to="participants.ParticipantTeam",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Host AWS access key. Used only when use host credentials is enabled.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="aws_account_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Host AWS account ID. Required alongside use host credentials for cross-account EKS scaling.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="aws_region",
            field=models.CharField(
                blank=True,
                default="us-east-1",
                help_text="AWS region holding this challenge's compute resources.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="aws_secret_access_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Host AWS secret key. Used only when use host credentials is enabled.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="banned_email_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="Individual email addresses barred from joining or submitting.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="blocked_email_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                help_text="Email domains barred from joining this challenge.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_usage_type",
            field=models.CharField(
                choices=[("paid", "Paid"), ("internal", "Internal")],
                db_index=True,
                default="paid",
                help_text="Paid challenges are billed to the host; internal ones are not.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="cli_version",
            field=models.CharField(
                blank=True,
                help_text="Minimum evalai-cli version required to submit.",
                max_length=20,
                null=True,
                verbose_name="evalai-cli version",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="cpu_only_jobs",
            field=models.BooleanField(
                default=False,
                help_text="Schedule submission jobs without GPUs.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="creator",
            field=models.ForeignKey(
                help_text="Challenge host team that owns and administers this challenge.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_creator",
                to="hosts.ChallengeHostTeam",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Full challenge overview rendered on the challenge landing page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="desired_worker_instance",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="EKS nodegroup size at creation. Autoscaling adjusts it from the pending submission count afterwards.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CV", "Computer Vision"),
                    ("NLP", "Natural Language Processing"),
                    ("RL", "Reinforcement Learning"),
                    ("MM", "Multimodal"),
                    ("AUD", "Audio"),
                    ("TAB", "Tabular"),
                ],
                help_text="Research area used to filter and group challenges.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="ec2_instance_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Instance ID of the provisioned EC2 worker. Set automatically.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="ec2_storage",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Root volume size for the EC2 worker, in GB.",
                verbose_name="EC2 storage (GB)",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="enable_forum",
            field=models.BooleanField(
                default=True,
                help_text="Show a discussion forum link on the challenge page.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the challenge closes. Also triggers worker and EKS nodegroup scale-down.",
                null=True,
                verbose_name="End Date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="ephemeral_storage",
            field=models.PositiveIntegerField(
                default=21,
                help_text="Fargate task ephemeral storage in GB. Minimum 21.",
                verbose_name="Ephemeral Storage (GB)",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="evaluation_details",
            field=models.TextField(
                blank=True,
                help_text="Explanation of how submissions are scored, shown to participants.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="evaluation_module_error",
            field=models.TextField(
                blank=True,
                help_text="Last error raised while importing the host's evaluation module. Set automatically.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="evaluation_script",
            field=models.FileField(
                default=False,
                help_text="Zip archive containing the evaluation code run against submissions.",
                upload_to=base.utils.RandomFileName("evaluation_scripts"),
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Show this challenge in the featured section of the home page.",
                verbose_name="Featured",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="forum_url",
            field=models.URLField(
                blank=True,
                help_text="External discussion forum URL, used when the forum is enabled.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="github_branch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Branch the GitHub sync workflow reads the challenge configuration from.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="github_repository",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source repository as account_name/repository_name, used by the GitHub sync workflow.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="has_prize",
            field=models.BooleanField(
                default=False,
                help_text="Whether a prize is offered. Shows the prize section on the challenge page.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="has_sponsors",
            field=models.BooleanField(
                default=False,
                help_text="Whether sponsors are listed. Shows the sponsors section on the challenge page.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Challenge logo shown in listings and on the challenge page.",
                null=True,
                upload_to=base.utils.RandomFileName("logos"),
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="inform_hosts",
            field=models.BooleanField(
                default=True,
                help_text="Send email notifications about this challenge to its hosts.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_disabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Hide the challenge and reject submissions. Also forces workers and the EKS nodegroup to zero.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_docker_based",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Participants submit code or container images rather than prediction files.",
                verbose_name="Is Docker Based",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_registration_open",
            field=models.BooleanField(
                default=True,
                help_text="Whether new participant teams may join.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_static_dataset_code_upload",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Two-stage code upload: participant code runs on EKS, then evaluation runs on the worker.",
                verbose_name="Is Static Dataset Code Upload Based",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="job_cpu_cores",
            field=models.CharField(
                blank=True,
                default="2000m",
                help_text="CPU request for a code upload submission's Kubernetes job, e.g. 2000m = 2 vCPU.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="job_memory",
            field=models.CharField(
                blank=True,
                default="8Gi",
                help_text="Memory request for a code upload submission's Kubernetes job, e.g. 8Gi.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="leaderboard_description",
            field=models.TextField(
                blank=True,
                help_text="Notes rendered above the leaderboard, e.g. how to read each metric.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="list_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
                help_text="Free-form tags shown on the challenge page and used in search.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="manual_participant_approval",
            field=models.BooleanField(
                default=False,
                help_text="Require a host to approve each team before it can submit.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="max_concurrent_submission_evaluation",
            field=models.PositiveIntegerField(
                default=100000,
                help_text="Maximum submissions evaluated at once across all participants.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="max_docker_image_size",
            field=models.BigIntegerField(
                blank=True,
                default=42949672960,
                help_text="Maximum participant image size in bytes. Default 42949672960 (40 GB).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="max_worker_instance",
            field=models.IntegerField(
                blank=True,
                default=10,
                help_text="EKS nodegroup ceiling, and the cap autoscaling may scale up to. Distinct from max ecs workers, which sizes Fargate.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="min_worker_instance",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="EKS nodegroup floor. Distinct from min ecs workers, which sizes Fargate.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="participant_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teams that have joined. Normally managed through registration rather than edited here.",
                to="participants.ParticipantTeam",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the challenge is visible to the public.",
                verbose_name="Publicly Available",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="queue",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Name of the SQS queue carrying this challenge's submission messages. Set automatically.",
                max_length=200,
                verbose_name="SQS queue name",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="queue_aws_region",
            field=models.CharField(
                blank=True,
                default="us-east-1",
                help_text="AWS region holding the SQS queue. May differ from the compute region.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="remote_evaluation",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Host runs evaluation on their own infrastructure; EvalAI provisions no workers.",
                verbose_name="Remote Evaluation",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="One or two line summary shown on challenge cards and in listings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="slack_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Slack incoming webhook for challenge notifications.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="slug",
            field=models.SlugField(
                help_text="URL identifier for the challenge. Generated from the title.",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="sqs_retention_period",
            field=models.PositiveIntegerField(
                default=345600,
                help_text="How long unread SQS messages are kept, in seconds. Default 345600 (4 days).",
                verbose_name="SQS Retention Period",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the challenge opens. Submissions are rejected before this time.",
                null=True,
                verbose_name="Start Date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="submission_guidelines",
            field=models.TextField(
                blank=True,
                help_text="Instructions shown to participants on the submission page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="submission_time_limit",
            field=models.PositiveIntegerField(
                default=86400,
                help_text="Per-submission wall-clock limit in seconds. Default 86400 (24 hours).",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="subnet_1_cidr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CIDR block for the first subnet of the code upload challenge VPC.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="subnet_2_cidr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CIDR block for the second subnet of the code upload challenge VPC.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="task_def_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ECS task definition ARN for the worker. Set automatically when the service is created or updated.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                help_text="Terms a participant must accept before submitting.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Challenge name shown in listings and on the challenge page.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="use_host_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Provision compute in the host's own AWS account using the credentials below.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="use_host_sqs",
            field=models.BooleanField(
                default=False,
                help_text="Use the host's own SQS queue instead of EvalAI's.",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="uses_ec2_worker",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Run the submission worker on a dedicated EC2 instance instead of Fargate.",
                verbose_name="Uses EC2 worker instance",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="vpc_cidr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CIDR block for the VPC created for this code upload challenge.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_ami_type",
            field=models.CharField(
                blank=True,
                default="AL2_x86_64_GPU",
                help_text="EKS node AMI type. Use a GPU variant unless CPU only jobs is enabled.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_cpu_cores",
            field=models.IntegerField(
                blank=True,
                default=512,
                help_text="Fargate worker CPU in ECS CPU units (1024 = 1 vCPU).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_disk_size",
            field=models.IntegerField(
                blank=True,
                default=100,
                help_text="Disk size of each EKS node, in GB.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override the worker container image. Leave blank to use the EvalAI default.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_instance_type",
            field=models.CharField(
                blank=True,
                default="g4dn.xlarge",
                help_text="EC2 instance type for the EKS nodes that run code upload submissions.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="worker_memory",
            field=models.IntegerField(
                blank=True,
                default=1024,
                help_text="Fargate worker memory in MiB (1024 = 1 GB).",
                null=True,
            ),
        ),
    ]
