# Generated by Django 2.2.20 on 2026-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0131_challengeevaluationcluster_nodegroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="use_fifo_sqs",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Use a FIFO SQS queue for strict per-phase submission "
                    "ordering. Do not toggle after queue creation; provision "
                    "a new challenge instead."
                ),
            ),
        ),
    ]
