# Generated by Django 2.2.20 on 2026-07-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0132_challenge_use_fifo_sqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="min_ecs_workers",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Autoscaling floor: min workers kept alive when the SQS queue is empty. 0 allows scale-to-zero.",
                null=True,
            ),
        ),
    ]
