# Generated by Django 2.2.20 on 2026-08-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0133_alter_challenge_min_ecs_workers_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="use_fifo_sqs",
            field=models.BooleanField(
                default=False,
                help_text="Use a FIFO SQS queue with per-team ordering within a phase (MessageGroupId=phase_pk-participant_team_pk) so different teams can be processed in parallel by ECS workers. MessageDeduplicationId is unique per enqueue (submission_pk plus UUID), so intentional resume/republish is not dropped; SQS only deduplicates identical MessageDeduplicationId values within a five-minute window. Do not toggle after queue creation; provision a new challenge instead. After changing group-id strategy, purge or drain the FIFO queue so legacy messages do not share the queue with a new grouping scheme.",
            ),
        ),
    ]
