# Generated by Django 2.2.20 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0134_alter_challenge_use_fifo_sqs_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="min_ecs_workers",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Autoscaling floor: min workers kept alive when the SQS queue is empty. 0 allows scale-to-zero.",
                null=True,
            ),
        ),
    ]
