# Generated by Django 2.2.20 on 2026-08-20 00:00

import challenges.models
from django.db import migrations, models


def grandfather_existing_challenges(apps, schema_editor):
    Challenge = apps.get_model("challenges", "Challenge")
    Challenge.objects.all().update(max_allowed_phases=None)


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0135_alter_challenge_min_ecs_workers_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_allowed_phases",
            field=models.PositiveIntegerField(
                blank=True,
                default=challenges.models.get_default_max_challenge_phases,
                help_text=(
                    "Maximum number of challenge phases a host may configure. "
                    "Leave blank for no limit (legacy challenges). New "
                    "challenges use the configured default; increase this "
                    "after host approval."
                ),
                null=True,
                verbose_name="Maximum Allowed Phases",
            ),
        ),
        migrations.RunPython(
            grandfather_existing_challenges,
            migrations.RunPython.noop,
        ),
    ]
