global:
  scrape_interval: 30s
  external_labels:
    monitor: 'evalai-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']
      
  - job_name: 'statsd'
    metrics_path: '/statsd/metrics'
    static_configs:
      - targets: ['statsd:9102']
  
  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'push_gateway'
    metrics_path: '/push_gateway/metrics'
    static_configs:
      - targets: ['push_gateway:9091']
