global:
  scrape_interval: 30s
  external_labels:
    monitor: 'evalai-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']
      
  - job_name: 'statsd'
    metrics_path: '/statsd/metrics'
    static_configs:
      - targets: ['statsd:9102']
