global:
  scrape_interval: 30s
  external_labels:
    monitor: 'evalai-monitor'

scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']

  - job_name: 'django-prometheus'
    metrics_path: '/api/prometheus/metrics'
    static_configs:
      - targets: ['django:8000']
