groups:
- name: API-Threshold-Exceeded
  rules:
  - alert: API-Threshold-Exceeded-4XX
    expr: rate(django_request_count{job="statsd",method="GET",status=~"4..",view=~"jobs:.*|challenges:.*"}[5m]) > 0.3
    for: 5m
    annotations:
      title: 'API-Threshold-Exceeded - 4XX'
      description: '•*{{ $labels.view }}* had *{{ $value | printf "%.1f" }}* QPS rate with the response code of *4XX* in the last 5 minutes'
    labels:
      severity: 'critical'
      group: 'api'

  - alert: API-Threshold-Exceeded-5XX
    expr: rate(django_request_counter{job="statsd",method="GET",status=~"5..",view=~"jobs:.*|challenges:.*"}[5m]) > 0.3
    for: 5m
    annotations:
      title: 'API-Threshold-Exceeded - 5XX'
      description: '•*{{ $labels.view }}* had *{{ $value | printf "%.1f" }}* QPS rate with the response code of *5XX* in the last 5 minutes'
    labels:
      severity: 'critical'
      group: 'api'

- name: Instance-Status
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    annotations:
      title: "Instance(s) Down"
      description: "•*{{ $labels.instance }}* of prometheus job *{{ $labels.job }}* has been down for more than 5 minutes"
    labels:
      severity: major
      group: 'instance'
