groups:
- name: API-Threshold-Exceeded
  rules:
  - alert: API-Threshold-Exceeded-4XX
    expr: increase(django_http_responses_total_by_status_view_method_total{job="django",method="GET",status=~"4..",view=~"jobs:.*|challenges:.*"}[5m]) > 100
    for: 5m
    annotations:
      title: 'API-Threshold-Exceeded - 4XX'
      description: '•*{{ $labels.view }}* had *{{ $value | printf "%.1f" }}* API calls with the response code of *4XX* in the last 5 minutes'
    labels:
      severity: 'critical'
      group: 'api'

  - alert: API-Threshold-Exceeded-5XX
    expr: increase(django_http_responses_total_by_status_view_method_total{job="django",method="GET",status=~"5..",view=~"jobs:.*|challenges:.*"}[5m]) > 100
    for: 5m
    annotations:
      title: 'API-Threshold-Exceeded - 5XX'
      description: '•*{{ $labels.view }}* had *{{ $value | printf "%.1f" }}* API calls with the response code of *5XX* in the last 5 minutes'
    labels:
      severity: 'critical'
      group: 'api'

- name: Instance-Status
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    annotations:
      title: "Instance(s) Down"
      description: "•*{{ $labels.instance }}* of prometheus job *{{ $labels.job }}* has been down for more than 5 minutes"
    labels:
      severity: major
      group: 'instance'
