# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participantteam_participantteammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='challenge',
        ),
        migrations.AddField(
            model_name='participantteam',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='participants.Participant'),
        ),
    ]
