# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("participants", "0004_add_created_by_participant_team")]

    operations = [
        migrations.RemoveField(model_name="participantteam", name="challenge")
    ]
