# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("participants", "0007_add_team_participant")]

    operations = [
        migrations.AlterField(
            model_name="participantteam",
            name="team_name",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
