# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("participants", "0009_participantteam_team_url")]

    operations = [
        migrations.AlterField(
            model_name="participantteam",
            name="team_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        )
    ]
