# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("participants", "0010_Add_blank_in_team_URL")]

    operations = [
        migrations.AddField(
            model_name="participantteam",
            name="docker_repository_uri",
            field=models.CharField(blank=True, default="", max_length=1000),
        )
    ]
