# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "participants",
            "0011_add_docker_repository_uri_for_each_participant_team",
        )
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantteam", name="docker_repository_uri"
        )
    ]
