# Generated by Django 2.2.8 on 2020-11-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', 'Add_blank_in_host_team_URL'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengehost',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hosts.ChallengeHostTeam'),
        ),
        migrations.AlterField(
            model_name='challengehost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengehostteam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_host_team_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
