# Generated by Django 2.2.20 on 2025-04-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0001_challengehostteaminvitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challengehostteaminvitation",
            old_name="team",
            new_name="challenge_host_team",
        ),
        migrations.AlterField(
            model_name="challengehostteaminvitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="challengehostteaminvitation",
            name="invitation_key",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="challengehostteaminvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengehostteaminvitation",
            unique_together={("email", "challenge_host_team")},
        ),
        migrations.AlterModelTable(
            name="challengehostteaminvitation",
            table="challenge_host_team_invitation",
        ),
    ]
