# Generated by Django 2.2.20 on 2025-04-17 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20250417_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengehostteaminvitation',
            old_name='challenge_host_team',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='challengehostteaminvitation',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='challengehostteaminvitation',
            name='invitation_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='challengehostteaminvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_host_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='challengehostteaminvitation',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='challengehostteaminvitation',
            table='challenge_host_team_invitations',
        ),
    ]
