# Generated by Django 2.2.20 on 2025-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0003_auto_20250417_2245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengehostteaminvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
