# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hosts", "0003_challengehostteam_team_url")]

    operations = [
        migrations.AlterField(
            model_name="challengehostteam",
            name="team_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        )
    ]
