# name: autoupdate
# This workflow triggers if commits are pushed to the master branch
on:
  push:
    branches:
      - master

jobs:
  autoupdate:
    name: Auto Update
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Use the Docker container for the auto-update action
      - name: Auto Update with Docker
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          # Step 2: Set environment variables
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: 'false'
          PR_FILTER: 'labelled'
          PR_LABELS: 'can-be-merged'
          EXCLUDED_LABELS: 'needs-more-work'
          MERGE_MSG: 'Branch was auto-updated.'
          RETRY_COUNT: '10'
          RETRY_SLEEP: '300'
          MERGE_CONFLICT_ACTION: 'fail'
